### ISSUE TITLE
수박게임 공용 TODO(2)

### ISSUE THREAD

**Issue by kledyu** [INU-Fake-Developers/watermelon-game-kled#2]
- [x] 고른 이미지 편집하기
- [x] 편집한 이미지 변환 후 프로젝트 폴더에 추가하기
- [x] 로컬 환경에서 테스트하기

**Comment by kledyu** [comment]
Closed
